title: "Predicting Student's Success with Academic Performance Record"
author: "Bill Wan, Katherine Chen, Hancheng Qin, Yili Tang"
date: "2023-12-2"
sphinx:
  config:
    bibtex_reference_style: author_year
execute:
  execute_notebooks: force 
bibtex_bibfiles:
  - references.bib
html_theme_options:
  # Commented out footer_info and copyright
  #footer_info: "Custom footer text goes here. Omit or customize as needed."
  #copyright: "Copyright Â© 2023 by the authors. All rights reserved."
  show_sidebar: false
  logo: false
  logo_name: false
html_css_files:
  - 'custom.css'
