name: 'DSCI522_group15'
channels:
  - conda-forge
  - defaults
dependencies:
  - altair=5.1.2=pyhd8ed1ab_0
  - appnope=0.1.3=pyhd8ed1ab_0
  - asttokens=2.4.0=pyhd8ed1ab_0
  - atk-1.0=2.38.0=hcb7b3dd_1
  - attrs=23.1.0=pyh71513ae_1
  - aws-c-auth=0.7.4=h2ed40ff_1
  - aws-c-cal=0.6.2=h12c43c8_2
  - aws-c-common=0.9.3=hb547adb_0
  - aws-c-compression=0.2.17=h12c43c8_3
  - aws-c-event-stream=0.3.2=h88fe898_1
  - aws-c-http=0.7.13=he062130_1
  - aws-c-io=0.13.32=h5bd1e48_6
  - aws-c-mqtt=0.9.6=h3ffe4bb_2
  - aws-c-s3=0.3.17=hf064be9_3
  - aws-c-sdkutils=0.1.12=h12c43c8_2
  - aws-checksums=0.1.17=h12c43c8_2
  - aws-crt-cpp=0.24.2=h6758146_0
  - aws-sdk-cpp=1.11.156=ha282cf0_4
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=pyhd8ed1ab_3
  - backports.functools_lru_cache=1.6.5=pyhd8ed1ab_0
  - beautifulsoup4=4.12.2=pyha770c72_0
  - bleach=6.1.0=pyhd8ed1ab_0
  - brotli=1.1.0=hb547adb_1
  - brotli-bin=1.1.0=hb547adb_1
  - brotli-python=1.1.0=py310h1253130_1
  - bzip2=1.0.8=h3422bc3_4
  - c-ares=1.20.1=h93a5062_0
  - ca-certificates=2023.7.22=hf0a4a13_0
  - cairo=1.16.0=hc5b65c1_1017
  - certifi=2023.7.22=pyhd8ed1ab_0
  - charset-normalizer=3.3.0=pyhd8ed1ab_0
  - comm=0.1.4=pyhd8ed1ab_0
  - contourpy=1.1.1=py310h38f39d4_1
  - cycler=0.12.1=pyhd8ed1ab_0
  - debugpy=1.8.0=py310h1253130_1
  - decorator=5.1.1=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - entrypoints=0.4=pyhd8ed1ab_0
  - exceptiongroup=1.1.3=pyhd8ed1ab_0
  - executing=1.2.0=pyhd8ed1ab_0
  - expat=2.5.0=hb7217d7_1
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=hab24e00_0
  - fontconfig=2.14.2=h82840c6_0
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - fonttools=4.43.1=py310hd125d64_0
  - freetype=2.12.1=hadb7bae_2
  - fribidi=1.0.10=h27ca646_0
  - gdk-pixbuf=2.42.10=h15fa40c_4
  - gettext=0.21.1=h0186832_0
  - gflags=2.2.2=hc88da5d_1004
  - giflib=5.2.1=h1a8c8d9_3
  - glog=0.6.0=h6da1cb0_0
  - graphite2=1.3.13=h9f76cd9_1001
  - graphviz=8.1.0=h10878c0_0
  - gtk2=2.24.33=h57013de_2
  - gts=0.7.6=he42f4ea_4
  - harfbuzz=8.2.1=hf1a6348_0
  - icu=73.2=hc8870d7_0
  - idna=3.4=pyhd8ed1ab_0
  - importlib-metadata=6.8.0=pyha770c72_0
  - importlib_metadata=6.8.0=hd8ed1ab_0
  - importlib_resources=6.1.0=pyhd8ed1ab_0
  - ipykernel=6.25.2=pyh1050b4e_0
  - ipython=8.16.1=pyh31c8845_0
  - ipywidgets=8.1.1=pyhd8ed1ab_0
  - jedi=0.19.1=pyhd8ed1ab_0
  - jinja2=3.1.2=pyhd8ed1ab_1
  - joblib=1.3.2=pyhd8ed1ab_0
  - jsonschema=4.19.1=pyhd8ed1ab_0
  - jsonschema-specifications=2023.7.1=pyhd8ed1ab_0
  - jupyter_client=8.3.1=pyhd8ed1ab_0
  - jupyter_core=5.3.2=py310hbe9552e_0
  - jupyterlab_pygments=0.2.2=pyhd8ed1ab_0
  - jupyterlab_widgets=3.0.9=pyhd8ed1ab_0
  - kiwisolver=1.4.5=py310h38f39d4_1
  - krb5=1.21.2=h92f50d5_0
  - lcms2=2.15=hf2736f0_3
  - lerc=4.0.0=h9a09cb3_0
  - libabseil=20230802.1=cxx17_h13dd4ca_0
  - libarrow=13.0.0=h5325880_8_cpu
  - libblas=3.9.0=18_osxarm64_openblas
  - libbrotlicommon=1.1.0=hb547adb_1
  - libbrotlidec=1.1.0=hb547adb_1
  - libbrotlienc=1.1.0=hb547adb_1
  - libcblas=3.9.0=18_osxarm64_openblas
  - libcrc32c=1.1.2=hbdafb3b_0
  - libcurl=8.3.0=hc52a3a8_0
  - libcxx=16.0.6=h4653b0c_0
  - libdeflate=1.19=hb547adb_0
  - libedit=3.1.20191231=hc8eb9b7_2
  - libev=4.33=h642e427_1
  - libevent=2.1.12=h2757513_1
  - libexpat=2.5.0=hb7217d7_1
  - libffi=3.4.2=h3422bc3_5
  - libgd=2.3.3=hfdf3952_9
  - libgfortran=5.0.0=13_2_0_hd922786_1
  - libgfortran5=13.2.0=hf226fd6_1
  - libglib=2.78.0=h24e9cb9_0
  - libgoogle-cloud=2.12.0=h5a37b55_3
  - libgrpc=1.58.1=h941e00e_0
  - libiconv=1.17=he4db4b2_0
  - libjpeg-turbo=3.0.0=hb547adb_1
  - liblapack=3.9.0=18_osxarm64_openblas
  - libnghttp2=1.52.0=hae82a92_0
  - libopenblas=0.3.24=openmp_hd76b1f2_0
  - libpng=1.6.39=h76d750c_0
  - libprotobuf=4.24.3=hf590ac1_0
  - librsvg=2.56.3=h0db3404_0
  - libsodium=1.0.18=h27ca646_1
  - libsqlite=3.43.0=hb31c410_0
  - libssh2=1.11.0=h7a5bd25_0
  - libthrift=0.19.0=h026a170_1
  - libtiff=4.6.0=ha8a6c65_2
  - libtool=2.4.7=hb7217d7_0
  - libutf8proc=2.8.0=h1a8c8d9_0
  - libwebp=1.3.2=hf30222e_1
  - libwebp-base=1.3.2=hb547adb_0
  - libxcb=1.15=hf346824_0
  - libxml2=2.11.5=h25269f3_1
  - libzlib=1.2.13=h53f4e23_5
  - lightgbm=4.0.0=py310h980d568_0
  - llvm-openmp=17.0.2=h1c12783_0
  - lz4-c=1.9.4=hb7217d7_0
  - markupsafe=2.1.3=py310h2aa6e3c_1
  - matplotlib=3.8.0=py310hb6292c7_1
  - matplotlib-base=3.8.0=py310hd1c642d_1
  - matplotlib-inline=0.1.6=pyhd8ed1ab_0
  - munkres=1.1.4=pyh9f0ad1d_0
  - nbclient=0.8.0=pyhd8ed1ab_0
  - nbconvert=7.9.2=pyhd8ed1ab_0
  - nbconvert-core=7.9.2=pyhd8ed1ab_0
  - nbconvert-pandoc=7.9.2=pyhd8ed1ab_0
  - nbformat=5.9.2=pyhd8ed1ab_0
  - ncurses=6.4=h7ea286d_0
  - nest-asyncio=1.5.6=pyhd8ed1ab_0
  - numpy=1.26.0=py310he2cad68_0
  - openjpeg=2.5.0=h4c1507b_3
  - openssl=3.1.4=h0d3ecfb_0
  - orc=1.9.0=hcd02cb2_3
  - packaging=23.2=pyhd8ed1ab_0
  - pandas=2.1.1=py310h5924a0a_1
  - pandoc=3.1.3=hce30654_0
  - pandocfilters=1.5.0=pyhd8ed1ab_0
  - pango=1.50.14=hcf40dda_2
  - parso=0.8.3=pyhd8ed1ab_0
  - patsy=0.5.3=pyhd8ed1ab_0
  - pcre2=10.40=hb34f9b4_0
  - pexpect=4.8.0=pyh1a96a4e_2
  - pickleshare=0.7.5=py_1003
  - pillow=10.0.1=py310hdfbc14a_2
  - pip=23.2.1=pyhd8ed1ab_0
  - pixman=0.42.2=h13dd4ca_0
  - pkgutil-resolve-name=1.3.10=pyhd8ed1ab_1
  - platformdirs=3.11.0=pyhd8ed1ab_0
  - prompt-toolkit=3.0.39=pyha770c72_0
  - prompt_toolkit=3.0.39=hd8ed1ab_0
  - protobuf=4.24.3=py310hc08086b_1
  - psutil=5.9.5=py310h2aa6e3c_1
  - pthread-stubs=0.4=h27ca646_1001
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pure_eval=0.2.2=pyhd8ed1ab_0
  - pyarrow=13.0.0=py310h382c99a_8_cpu
  - pygments=2.16.1=pyhd8ed1ab_0
  - pyparsing=3.1.1=pyhd8ed1ab_0
  - pysocks=1.7.1=pyha2e5f31_6
  - python=3.10.0=h43b31ca_3_cpython
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python-fastjsonschema=2.18.1=pyhd8ed1ab_0
  - python-graphviz=0.20.1=pyh22cad53_0
  - python-tzdata=2023.3=pyhd8ed1ab_0
  - python_abi=3.10=4_cp310
  - pytz=2023.3.post1=pyhd8ed1ab_0
  - pyzmq=25.1.1=py310h30b7201_1
  - re2=2023.03.02=hc5e2d97_0
  - readline=8.2=h92ec313_1
  - referencing=0.30.2=pyhd8ed1ab_0
  - requests=2.31.0=pyhd8ed1ab_0
  - rpds-py=0.10.4=py310hd442715_0
  - scikit-learn=1.3.1=py310h417b086_1
  - scipy=1.11.3=py310hd1cfc7d_1
  - seaborn=0.13.0=hd8ed1ab_0
  - seaborn-base=0.13.0=pyhd8ed1ab_0
  - setuptools=68.2.2=pyhd8ed1ab_0
  - six=1.16.0=pyh6c4a22f_0
  - snappy=1.1.10=h17c5cce_0
  - soupsieve=2.5=pyhd8ed1ab_1
  - sqlite=3.43.0=h203b68d_0
  - stack_data=0.6.2=pyhd8ed1ab_0
  - statsmodels=0.14.0=py310h50ce23c_2
  - threadpoolctl=3.2.0=pyha21a80b_0
  - tinycss2=1.2.1=pyhd8ed1ab_0
  - tk=8.6.13=hb31c410_0
  - toolz=0.12.0=pyhd8ed1ab_0
  - tornado=6.3.3=py310h2aa6e3c_1
  - traitlets=5.11.2=pyhd8ed1ab_0
  - typing-extensions=4.8.0=hd8ed1ab_0
  - typing_extensions=4.8.0=pyha770c72_0
  - tzdata=2023c=h71feb2d_0
  - unicodedata2=15.1.0=py310h2aa6e3c_0
  - urllib3=2.0.6=pyhd8ed1ab_0
  - vega_datasets=0.9.0=pyhd3deb0d_0
  - vegafusion=1.4.0=pyhd8ed1ab_0
  - vegafusion-jupyter=1.4.0=pyhd8ed1ab_0
  - vegafusion-python-embed=1.4.1=py310had9acf8_0
  - vl-convert-python=0.14.0=py310h2aa6e3c_0
  - wcwidth=0.2.8=pyhd8ed1ab_0
  - webencodings=0.5.1=pyhd8ed1ab_2
  - wheel=0.41.2=pyhd8ed1ab_0
  - widgetsnbextension=4.0.9=pyhd8ed1ab_0
  - wordcloud=1.9.2=py310h2aa6e3c_1
  - xorg-libxau=1.0.11=hb547adb_0
  - xorg-libxdmcp=1.1.3=h27ca646_0
  - xz=5.2.6=h57fd34a_0
  - zeromq=4.3.4=hbdafb3b_1
  - zipp=3.17.0=pyhd8ed1ab_0
  - zlib=1.2.13=h53f4e23_5
  - zstd=1.5.5=h4f39d0f_0
  - pip:
      - alabaster==0.7.13
      - annotated-types==0.6.0
      - astunparse==1.6.3
      - babel==2.13.0
      - click==8.1.7
      - cloudpickle==3.0.0
      - dill==0.3.7
      - docutils==0.20.1
      - fica==0.3.1
      - future==0.18.3
      - greenlet==2.0.2
      - hpsklearn==1.0.3
      - hyperopt==0.2.7
      - imageio==2.31.5
      - imagesize==1.4.1
      - ipylab==1.0.0
      - jupytext==1.15.2
      - markdown-it-py==3.0.0
      - mdit-py-plugins==0.4.0
      - mdurl==0.1.2
      - mglearn==0.2.0
      - mistune==3.0.2
      - networkx==3.2
      - otter-grader==5.2.2
      - playwright==1.38.0
      - py4j==0.10.9.7
      - pydantic==2.4.2
      - pydantic-core==2.10.1
      - pyee==9.0.4
      - python-on-whales==0.65.0
      - pyyaml==6.0.1
      - snowballstemmer==2.2.0
      - sphinx==7.2.6
      - sphinxcontrib-applehelp==1.0.7
      - sphinxcontrib-devhelp==1.0.5
      - sphinxcontrib-htmlhelp==2.0.4
      - sphinxcontrib-jsmath==1.0.1
      - sphinxcontrib-qthelp==1.0.6
      - sphinxcontrib-serializinghtml==1.1.9
      - toml==0.10.2
      - tqdm==4.66.1
      - typer==0.9.0
      - wrapt==1.15.0
prefix: /Users/tangyili/miniconda3/envs/571
